using System;
using System.Collections.Generic;

namespace Bond
{
    public class ScriptGenerator
    {
        private readonly string indent = new string(' ', 4);

        internal List<string> Lines { get; } = new List<string>();

        public virtual void WriteFileStart()
        {
            Lines.Clear();
            Lines.Add($"// Automatically generated by Bond at {DateTime.Now:yyyy-MM-dd HH:mm:ss}.");
        }

        public virtual void WriteFileEnd()
        {
        }

        public virtual void WriteNamespaceStart(string name)
        {
            Lines.Add("");
            Lines.Add($"declare module {name} {{");
        }

        public virtual void WriteNamespaceEnd()
        {
            Lines.Add("}");
        }

        public virtual void WriteClassStart(string name)
        {
            Lines.Add("");
            Lines.Add($"{indent}interface {name} {{");
        }

        public virtual void WriteClassProperty(string name, string type)
        {
            Lines.Add($"{indent}{indent}{name}: {type};");
        }

        public virtual void WriteClassEnd()
        {
            Lines.Add($"{indent}}}");
        }

        public virtual void WriteEnumStart(string name)
        {
            Lines.Add("");
            Lines.Add($"{indent}const enum {name} {{");
        }

        public virtual void WriteEnumConstant(string name, Enum value)
        {
            Lines.Add($"{indent}{indent}{name} = {value:D},");
        }

        public virtual void WriteEnumEnd()
        {
            Lines.Add($"{indent}}}");
        }
    }
}
